import Head from "next/head";
import { Inter } from "@next/font/google";
import { use, useState } from "react";
import { useEffect, useCallback } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [sum, setSum] = useState(0);
  const [check, setCheck] = useState(false);
  const [effect, setEffect] = useState(false);
  const numbers = [19, 35];

  const DetectKeyDown = (e) => {
    if (e.key == "Enter") {
      return CheckSum(sum);
    }
  };

  const CheckSum = (value) => {
    if (value === "54") {
      return setCheck(true);
    }
  };

  // const HandleKeyDown = (e) => {
  //   if (e.key === "Enter") {
  //     return CheckSum(sum);
  //   }
  // };

  // useEffect(() => {
  //   HandleKeyDown;
  // }, []);
  
  return (
    <>
      <Head>
        <title>Hurelsuh motherfucker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-hurelsuh">
        <div className="h-full flex justify-center items-center">
          {check == false ? (
            <div className="flex flex-col w-300px md:w-[600px] gap-y-[30px] items-center">
              <h1 className="text-[30px] md:text-[50px] font-bold text-center">
                Answer the question
              </h1>
              <div
                className={`${
                  effect && "animate-wiggle border-red-400 text-red-400 "
                } flex w-full justify-center gap-x-2 md:gap-x-4 items-center border-4 rounded-[12px] px-2 py-4 md:px-0 md:py-2`}
                onAnimationEnd={() => setEffect(false)}
              >
                <h2 className=" text-[30px] md:text-[40px] font-bold">
                  {numbers[0]}+{numbers[1]}=
                </h2>
                <div>
                  <input
                    className="py-1.5 md:py-1 w-[60%] md:text-[16px] text-[14px] mt-[2px] md:mt-[4px] border-y-4 border-l-4 rounded-l-[12px] px-[6px] bg-slate-400 focus:outline-none focus:ring-blue-400 focus:border-blue-400 hover:border-blue-300 duration-200"
                    type="number"
                    id="sum"
                    onChange={(e) => {
                      setSum(e.target.value);
                    }}
                    // onKeyDown={HandleKeyDown}
                  />
                  <button
                    className="border-4 rounded-r-[12px] px-3 md:px-6 py-1 font-bold md:text-[16px] bg-blue-300 hover:bg-blue-400 duration-200 transition"
                    onClick={() => {
                      CheckSum(sum);
                      setEffect(true);
                    }}
                  >
                    Enter
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className="w-[500px] animate-shake">
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/4/4b/Mongolian_Prime_Minister_Khurelsukh_Ukhnaa_in_2018.jpg"
                alt=""
              />
            </div>
          )}
        </div>
      </div>
    </>
  );
}
